### ISSUE TITLE
Incomplete traces: Exception text missing

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.jdbc#105]
In the logs coming from JDBCRun when there is a data type mismatch:
`CDIST2821W A SQL exception occurred. The exception is {0} .`
Looks like the exception string is not being inserted into the message.

**Comment by lpkamesam** [comment]
I have also noticed the issues where I don't receive {sqlCode=0,sqlState="",sqlMessage=""

**Comment by anouri** [comment]
If your database is a Db2, you have to set the parameter etrieveMessagesFromServerOnGetMessage=true; in jdbcUrl to get sqlMessage.

jdbcUrl : "jdbc:db2://tank143.fyre.ibm.com:50000/TESTDB2:retrieveMessagesFromServerOnGetMessage=true;" ;

More details in 
https://github.com/IBMStreams/streamsx.jdbc/wiki/How-to-connect-to-a-DB2-database-via-JDBC-toolkit

**Comment by anouri** [comment]
The **JDBCRun** operator checks now:
if the database is a Db2 it adds the property "retrieveMessagesFromServerOnGetMessage=true;" to URL to retrieve full SQL error message

```
if ( (jdbcUrl.contains("db2")) && (!jdbcUrl.contains("retrieveMessagesFromServerOnGetMessage") ))
{
	jdbcUrl = jdbcUrl + ":retrieveMessagesFromServerOnGetMessage=true;" ;
}
```
More details in:
https://www.ibm.com/support/knowledgecenter/fi/SSEPGG_9.7.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_tjvjcerr.html

**Comment by anouri** [comment]
Correction delivered in:
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.8.0
