### ISSUE TITLE
db2 installation folder was not specified in the script

### ISSUE THREAD

**Issue by jddwibfiebzEwifbxrinfegfn** [IBMStreams/streamsx.jdbc#109]
Hello, 

`https://github.com/IBMStreams/streamsx.jdbc/wiki/How-to-setup-a-SSL-configuration-in-DB2-and-in-JDBC-toolkit`

The instance had not DB2 Install folder, or any other folder with the `keytool` tool, in it's $PATH variable and it caused the error on line 50: keytool could not be found.

Usually, the keytool is also in:
- <DB2INSTALL_FOLDER_VERSION>/java/jdk64/bin/keytool
- <DB2INSTALL_FOLDER_VERSION>/java/jdk64/jre/bin/keytool

**Comment by anouri** [comment]
Hi Igor
The keytool is a part of JDK package.
If you have installed any JDK on your Db2 Server you can add the following line to your .bashrc file.
Add export PATH=$PATH:/path/to/jre/bin to your .bashrc file. 
Or 
export $DB2INSTALL_FOLDER_VERSION/java/jdk64/bin/
I will write a hint about the path of keytool in the WiKi.
Thank you.

**Comment by anouri** [comment]
The documentation in wiki upgraded with a hint about the path of `keytool`.

https://github.com/IBMStreams/streamsx.jdbc/wiki/How-to-setup-a-SSL-configuration-in-DB2-and-in-JDBC-toolkit

**Comment by anouri** [comment]
The documentation in wiki upgraded with a hint about the path of keytool.

https://github.com/IBMStreams/streamsx.jdbc/wiki/How-to-setup-a-SSL-configuration-in-DB2-and-in-JDBC-toolkit
