### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.jdbc#113]
Just noticed there are a couple of issues:
- Which databases and database versions are supported? I looked for  a list  of supported databases and their versions, but I could not find this information in the SPLDoc. Is this published somewhere?
- The samples all use a Makefile -  Can we update to include how to build with VS Code?

**Comment by anouri** [comment]
The info.xml file and the spldoc of streamsx.jdbc toolkit updated with additional information about the supported databases.

https://ibmstreams.github.io/streamsx.jdbc/doc/spldoc/html/tk$com.ibm.streamsx.jdbc/tk$com.ibm.streamsx.jdbc.html

**Comment by markheger** [comment]
SPLDoc updated, Makefile updated (#115 )
