### ISSUE TITLE
JDBCSample not cloud-ready

### ISSUE THREAD

**Issue by alexpogue** [IBMStreams/streamsx.jdbc#22]
JDBCSample writes its output data to a file, but users cannot access this file when running the sample in the cloud.

The "Use of FileSink to write output data" section of [Getting your SPL application ready for the cloud](https://developer.ibm.com/streamsdev/docs/getting-spl-application-ready-cloud/) says:
 > The FileSink operator will function correctly in the cloud, but since only the SPL application can access the file system on a Streams host in the cloud, writing data to files is of limited value.

**Comment by chanskw** [comment]
Is it possible for you to update the sample to make it cloud ready?

**Comment by chanskw** [comment]
I did not see the pull request... thanks for the contribution !  :+1:

**Comment by yiminy** [comment]
Thanks, Alex... Merged.

**Comment by alexpogue** [comment]
Any idea when the fix will be in a release? I'm writing an article, and I'd like point readers to a release rather than making them do a git pull and build the toolkit themselves.

**Comment by yiminy** [comment]
I created a new pre-release JDBC Toolkit v0.9.1, containing the update on JDBCSample. Thanks.
