### ISSUE TITLE
JDBCRun error port needs to be a notification port

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.jdbc#32]
In my application, I would like to get a notification upon the following events:

1)  when JDBCRun lost connection to the server.
2)  when JDBCRun successfully connects to the remote server, mainly after a connection is lost.

Currently, we only emit a tuple on the error port upon errors.  Is it possible to convert the error port to a notification port, so we get events on when we lose or establish connection?

@ankitpas @yiminy what do you think?

Thanks!

**Comment by anouri** [comment]
corrected in JDBC release version 1.4.0
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.4.0
