### ISSUE TITLE
Release from master branch - 20160401

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.jdbc#38]
Please create a release of the latest code from master .

Please create a release proposal with the following information:

* Toolkit Version Number
* What version of Streams will this support?
* Confirmation about what testing is done and status
* What's changed and new?

**Comment by yiminy** [comment]
The pre-release v0.9.3 for JDBC Toolkit created at https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v0.9.3

**Comment by yiminy** [comment]
JDBC Toolkit v0.9.3 pre-release proposal

**Toolkit Version Number**: 0.9.3
**What version of Streams will this support?** Streams 4.0.X & 4.1.x
**Confirmation about what testing is done and status**: 
All JUnit tests passed. The test cases include: 

- JDBC connection establishments (jdbcUrl, UserPassword, jdbcProperties)
- SQL statement execution with select statement and non-select statement (statement param, statementAttr param, transaction size/batch size, hasResultSetAttr)
- SQL error handling (SQLFailureAction, Error Port).

**What's changed and new?** JDBCRun operator enhancement on error processing and sqlStatusAttr parameter

**Comment by chanskw** [comment]
the version number in the info.xml needs to be bumped to 0.93

**Comment by chanskw** [comment]
+1 tested on Streams v4.0.1 and worked fine.

**Comment by yiminy** [comment]
Fixed a bug for JDBCRunErrorPort sample, and rebuilt the release 0.9.3.

**Comment by yiminy** [comment]
Tested JDBC samples and worked well.

**Comment by yiminy** [comment]
Ran JUnit tests on Streams 4.1 and all test cases worked fine.

**Comment by chanskw** [comment]
+1, tested with Streams 4.0.1, and works fine for me too.

**Comment by yiminy** [comment]
Created JDBC Toolkit release 0.9.3a [https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v0.9.3a](url)

note: v0.9.3 has been taken due to a deleted release.

**Comment by chanskw** [comment]
Done, closing
