### ISSUE TITLE
Release from v0.5 branch - 20160401

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.jdbc#39]
Please create a release of the latest code from master .

Please create a release proposal with the following information:

Toolkit Version Number
What version of Streams will this support?
Confirmation about what testing is done and status
What's changed and new?

**Comment by yiminy** [comment]
@chanskw could you help test on JDBC Toolkit v0.5 branch build on Streams 3.2.x (build: streamsx.jdbc.toolkits-0.5.0-20160401-1500.tgz)? Thanks...

**Toolkit Version Number**: v0.5.1
**What version of Streams will this support?** Streams 3.2.x
**Confirmation about what testing is done and status:** TBD 
**What's changed and new?** JDBCRun operator enhancement on error processing and sqlStatusAttr parameter

**Comment by chanskw** [comment]
-1 tested on 3.2.1 and the toolkit was not build correctly.
Please rebuild in Streams v3.2.1 env.

**Comment by yiminy** [comment]
Rebuilt JDBC Toolkit 0.5.1on Streams 3.2.1 environment.

**Toolkit Version Number**: v0.5.1
**What version of Streams will this support?** Streams 3.2.x
**Confirmation about what testing is done and status**: TBD
**What's changed and new?** JDBCRun operator enhancement on error processing and sqlStatusAttr parameter

**Comment by yiminy** [comment]
Tested JDBCRun operator samples on Streams 3.2.1, and worked well.

**Comment by chanskw** [comment]
+1 on v0.5.1 release.
Tested on Streams v3.2.1 and worked fine.

**Comment by chanskw** [comment]
done, closing
