### ISSUE TITLE
JDBCRun output port is set as punctuation free?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.jdbc#43]
In the JDBCRun operator, when we finish processing the result set, the operator submits a punctuation to mark the end of the result set.

However, in reading the SPDoc, the output port of the JDBCRun is set as punctuation free, which is incorrect.

**Comment by chanskw** [comment]
In my test case, I received a punctuation downstream even though the port is defined incorrectly

**Comment by anouri** [comment]
Correction delivered in version v1.3.4
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.4.3
