### ISSUE TITLE
Globalizing the toolkit

### ISSUE THREAD

**Issue by gertmark** [IBMStreams/streamsx.jdbc#46]
Provide log messages for different locales via unique message ids: German (de_DE), French (fr_FR), Italian (it_IT), Spanish (es_ES). Brazilian Portuguese (pt_BR), Japanese (ja_JP), Simplified Chinese (zh_CN), Russian (ru_RU), Traditional Chinese (zh_TW), Korean (ko_KR).

**Comment by anouri** [comment]
A new java class Message.java has been added.
The java property file messages/message_en_US.properties is ready for translation.
The messages_en_US.properties has 29 messages and 257 words.
The range of messages is CDIST2800 -> CDIST2899
The file JDBCRun.java and AbstractJDBCOperator.java have been adapted.
The JDBC sample has been tested with DB2 jdbc driver db2jcc4.jar.
Now I have asked Peter Nicholls how to check in the source files.

**Comment by petenicholls** [comment]
I created a branch for this: nlsupport (National language support).  Issue a pull request against that branch with your code and I will review it.

**Comment by anouri** [comment]
delivered in Version 1.2.0
