### ISSUE TITLE
Close connection after query

### ISSUE THREAD

**Issue by AlexCYang** [IBMStreams/streamsx.jdbc#55]
Hi, is there any plan to provide an option to close connection after query finishes or after a certain amount of idle time? We added the ability to close connection in our local jdbc toolkit as we don't want the session to open forever.

**Comment by anouri** [comment]
Yes.
We have planned to improve the JDBCRun operator with a new parameter “sessionIdelTmeOut”.
If the value of sessionIdelTmeOut parameter is set to a positive value the operator will close the connection after this time.
The correction will be delivered in the feature release.

**Comment by AlexCYang** [comment]
Hi @anouri , any update on this? I don't see a sessionIdleTimeOut in the releases yet.

**Comment by anouri** [comment]
The correction will be delivered in the next version of streamsx.jdbc  1.7.0

**Comment by anouri** [comment]
A new parameter **idleSessionTimeOut**  has been added to the **JDBCRun** operator.

This optional parameter specifies the Idle Session Time
Out in minute. Once the idle time value is reached, the operator close the database connection. 

Th timer restarts after a new query.

The value of the idleSessionTimeOut parameter must be greater than zero. ( at least 1 minute)

**Comment by anouri** [comment]
The correction has been delivered in release 1.7.0

https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.7.0

The following sample shows the use of idleSessionTimeOut parameter.

		stream<resultSchema> runSql = JDBCRun(genSQL)
		{
			param
				jdbcDriverLib : $jdbcDriverLib ;
				jdbcClassName : $jdbcClassName ;
				jdbcUrl : $jdbcUrl ;
				jdbcUser : $jdbcUser ;
				jdbcPassword : $jdbcPassword;
				statementAttr : SQLstatement;
				idleSessionTimeOut : 1;
		}

**Comment by AlexCYang** [comment]
Thanks! I'll give it a try and switch our dependency over

**Comment by AlexCYang** [comment]
Hi @anouri , I tested the new 1.7.0 jdbc toolkit and the idle session time out didn't work exactly as what's described. I have a beacon that's sending beacon into a jdbcRun operator and kicking off a simple query every 40 seconds, and have the idlesessiontimeout set to 1 min, and it appears that the session is been closed every minute, despite the fact that the query actually run every 40 seconds. Then I checked the code, and at https://github.com/IBMStreams/streamsx.jdbc/blob/v1.7.0/com.ibm.streamsx.jdbc/impl/java/src/com/ibm/streamsx/jdbc/JDBCRun.java#L487 the idle timeout thread is only started during initialization but not when a new query kicks off. Can you take a look at this? Thanks!

**Comment by anouri** [comment]
Hi Alex
It is correct the **idleSessionTimeOutThread**  starts only during the initialization.
It check every minutes the value of timer and the value of JDBCRn parameter  **idleSessionTimeOut**.
if (idleSessionTimeOutTimer >= idleSessionTimeOutMinute){
close connection)
}

If the operator get a new query, it sets the  value of variable idleSessionTimeOutTimer = 0;

Please test it with the following SPL sample:
  - query every 40 seconds
  - idleSessionTimeOut : 2; (2 minutes)
	
	       stream<rstring SQLstatement> createSelectTableSQL = Beacon()
		{
			param
				iterations : 200u ;
                                initDelay : 2.0;
                                period : 40.0;
			output
				createSelectTableSQL : SQLstatement = "SELECT * FROM TEST_TABLE" ;
		}


		stream<resultSchema> dropTable = JDBCRun(createSelectTableSQL)
		{
			param
				jdbcDriverLib : $jdbcDriverLib ;
				jdbcClassName : $jdbcClassName ;
				jdbcUrl : $jdbcUrl ;
				jdbcUser : $jdbcUser ;
				jdbcPassword : $jdbcPassword;
				statementAttr : SQLstatement;				
				idleSessionTimeOut : 2;
		}


I will check it again.

**Comment by anouri** [comment]
The problem was that the idleSessionTimeOutThread checked every minute the value of the timer 
and different between 2 SQL queries in your SPL application was 40 seconds. < 60
In this special case the idleSessionTimeOut closed the current JDBC connection after 1 minute and reconnect it in the next query. 
Not a bug. Only one not necessary action.

Now the thread checks  every second the value of timer.

**Comment by AlexCYang** [comment]
I understand the problem now and tested the 1.7.1 fix you have. It works as expected. Thanks for the quick response!

**Comment by anouri** [comment]
Correction delivered in:
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.7.1

**Comment by nmwaara** [comment]
The 'idleSessionTimeOut' parameter has been updated in order to fix the use case issues described in the above comment. The updated version of the toolkit is now available as the following official release (JDBC v1.7.1): https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.7.1

If new issues arise pertaining to this parameter, either re-open this issue or create a new Github issue on the streamsx.jdbc toolkit repository. Thank you.
