### ISSUE TITLE
SQL JDBC Errors - return sql error message

### ISSUE THREAD

**Issue by estherhi** [IBMStreams/streamsx.jdbc#60]
Include the sql error message in addition to sqlError and sqlState in the data structure.

**Comment by estherhi** [comment]
@anouri ^^^

**Comment by anouri** [comment]
@estherhi
I have checked the JDBC with DB2.
You are right. The second streams output port delivers only sqlCode and sqlStatus.
For example sqlCode: -601 sqlState: 42710
The JDBC driver from other databases delivers messages in sqLstatus but the DB” JDBC driver delivers only one code.
We have to change the Operator to send more Information ( sqlMessage  ) about the SQL Exception.
I am working on this issue.

**Comment by anouri** [comment]
@estherhi
Please check the branch feature-sqlmessage
https://github.com/IBMStreams/streamsx.jdbc/tree/feature-sqlmessage
I have added a new String sqlMessage to the SQLException jSqlStatus
Now the operator delivers in second output port   sqlCode, sqlState and sqlMessage
com.ibm.streamsx.jdbc.types/JDBCRunTypes.spl has been updated.
type
	JdbcSqlStatus_T = 	int32 sqlCode,
				        rstring sqlState,
				        rstring sqlMessage;

The samples/JDBCSample/com.ibm.streamsx.jdbc.sample.jdbcrun/JDBCRunSample.spl has been adapted.
It prints now the sqlMessage in errorprint
.....  " sqlMessage "+ error.sqlMessage);

**Comment by estherhi** [comment]
Thanks @anouri looking forward to the fix

**Comment by estherhi** [comment]
@anouri when will this fix be merged to master?

**Comment by anouri** [comment]
The new version v1.2.1 has been tested with DB2 and ORACLE databases.
The JDBCRun operator delivers in 2. output port information about the SQL error.
for example
If you try to select any data from a non existing TABLE, you get the following error message. 

DB2
sqlCode: -204, sqlState: 42704, sqlMessage: "DB2INST1.TEST2" is an undefined name.. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.16.53

ORACLE
sqlCode: 942, sqlState: 42000, sqlMessage: ORA-00942: table or view does not exist
Error : 942, Position : 14, Sql = SELECT * FROM TEST2, OriginalSql = SELECT * FROM TEST2, Error Msg = ORA-00942: table or view does not exist

For DB2
The jdbcUrl for DB2 has to contain this parameter at the end
retrieveMessagesFromServerOnGetMessage=true;
for example
jdbcUrl : "jdbc:db2://tank2.fyre.ibm.com:50000/TESTDB2:retrieveMessagesFromServerOnGetMessage=true;" ;

And the following example shows the jdbcUrl for ORACLE
jdbcUrl : "jdbc:oracle:thin:@tank2.fyre.ibm.com:1521/orcl.fyre.ibm.com" ;

**Comment by anouri** [comment]
corrected in JDBC 1.2.2
