### ISSUE TITLE
SPLDoc on website is out of date, please update

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.jdbc#64]
Please update SPLDoc, the toolkit version on it is 1.0.0.
But we have numerous new versions since then.  Thanks!

**Comment by anouri** [comment]
JDBC SPLDoc has been updated to version 1.2.2
http://ibmstreams.github.io/streamsx.jdbc/doc/spldoc/html/

**Comment by anouri** [comment]
JDBC SPLDoc has been updated to version 1.2.2
