### ISSUE TITLE
result of JDBCRun is empty

### ISSUE THREAD

**Issue by sunruns** [IBMStreams/streamsx.jdbc#65]
com.ibm.streamsx.jdbc version 1.2.2, oracle 11g , database codeset is amercian_america.utf8
ojdbc7.jar ( and also  tried ojdbc6.jar, ojdbc14.jar)
jdbcurl : jdbc:oracle:thin:@192.168.0.1:1521:orcl 
jdbcdrivername oracle.jdbc.driver.OracleDriver
JAVA_HOME streams java 1.8
very simple sqlstatement "select dummy from dual", JDBCRun without any error, but the printStringLn of result is empty.  sqlstate=0 
any hint to resolve this problem?

**Comment by sunruns** [comment]
namespace com.ibm.streamsx.jdbc.sample.jdbcrun; 
use com.ibm.streamsx.jdbc::*;
 use com.ibm.streamsx.jdbc.types::*;
composite JDBCRunSample {
 param
     expression<rstring> $jdbcDriverLib : getSubmissionTimeValue("jdbcDriverLib", "/home/streamsadmin/ojdbc7.jar");
     expression<rstring> $jdbcClassName : getSubmissionTimeValue("jdbcClassName", "oracle.jdbc.driver.OracleDriver");
     expression<rstring> $jdbcUrl : getSubmissionTimeValue("jdbcUrl","jdbc:oracle:thin:@10.154.145.39:1688:crmogg");
     expression<rstring> $jdbcUser : getSubmissionTimeValue("jdbcUser","username");
     expression<rstring> $jdbcPassword : getSubmissionTimeValue("jdbcPassword","password");
 type
     insertSchema =     int32         ID, 
                     rstring     FNAME,
                     rstring     LNAME,
                     int32         AGE,
                     rstring     GENDER,
                     float32     SCORE,
                     float64     TOTAL;
             rsSchema= rstring  dummy;
     selectSchema =     rstring        sql; 
 graph
     stream<insertSchema> pulse = Beacon() {
         param
             iterations : 1u ;
         output
             pulse : ID                 = 1,
                     FNAME            = "Mike",
                     LNAME            = "Ward",
                     AGE                = 31,
                     GENDER            = "M",
                     SCORE            = 33.3w,
                     TOTAL            = 912.3l;
     }
     stream<selectSchema> genSelect = Functor(pulse){
         output
             genSelect: sql="SELECT ‘dummy’ FROM dual";
     }
     (stream<rsSchema> select;stream<tuple<rsSchema> inTuple, JdbcSqlStatus_T error> errors) = JDBCRun(genSelect){
         param
             jdbcDriverLib: $jdbcDriverLib;
             jdbcClassName: $jdbcClassName;
             jdbcUrl: $jdbcUrl;
             jdbcUser: $jdbcUser;
             jdbcPassword: $jdbcPassword;
             statementAttr : sql;
             sqlStatusAttr  : "error";
             isolationLevel : "READ_COMMITTED";
             transactionSize :  2;
     }
             () as errorprint = Custom(errors)
             {
                  logic
                        onTuple errors : printStringLn("sqlcode:" + (rstring)error.sqlCode + ",sqlstate: " + error.sqlState + ",sqlmessage: " + error.sqlMessage);
             }
     () as printer = Custom(select) {
         logic onTuple select:
             printStringLn("result is " + dummy);
     }
}

**Comment by sunruns** [comment]
if use alias () as printer = Custom(select as I) { logic onTuple I: printStringLn("result is " + dummy); } the result is still empty

**Comment by sunruns** [comment]
if not set "transactionSize : 2;", there will be error "java.sql.SQLException : could not rollback with auto-commit set on"

**Comment by anouri** [comment]
Please check the following "how to" for ORACLE database:
https://github.com/IBMStreams/streamsx.jdbc/wiki/How-to-connect-to-an-ORACLE-database-via-JDBC-toolkit
