### ISSUE TITLE
SPLDOC overview for JDBCRun is not formatted correctly. 

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.jdbc#76]
Appears as a single paragraph, making it very hard to read.

http://ibmstreams.github.io/streamsx.jdbc/doc/spldoc/html/tk$com.ibm.streamsx.jdbc/op$com.ibm.streamsx.jdbc$JDBCRun.html

![image](https://user-images.githubusercontent.com/3769612/50230020-8c791500-0360-11e9-8d95-58c8e15da207.png)

**Comment by ddebrunner** [comment]
Actually the whole doc could do with a review, for example:

-  there are references to `transactionCount` parameter instead of `transactionSize`.
- No units specified for `commitInterval` and it's an `int32` which is usually for counts, so not sure how it differs from `transactionSize`.
- The overview states: _ In a consistent region, the configured value of the transactionSize is ignored._ but the `commitPolicy` doc indicates `transactionCount` is used.

**Comment by anouri** [comment]
We will improve the JDBC documentation in the next release.
