### ISSUE TITLE
Document JDBC driver setup.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.jdbc#77]
The docs are vague on how the JDBC driver jar location is specified.

Is `jdbcDriverLib` a runtime path, or can the driver be part of the sab file?

A section in `namespace-info.spl` would be really useful describing the setup.

**Comment by ddebrunner** [comment]
Especially how to setup for Streaming Analytics service.

**Comment by anouri** [comment]
The SAB file must include the JDBC jar libraries. 
For example in opt directory.
We will improve the JDBC documentation in the next release.
