### ISSUE TITLE
Support application configurations.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.jdbc#78]
Be useful to have application configurations be supported as the method to authentication, jdbc URL etc.

**Comment by markheger** [comment]
The new operator parameter "credentials" should be also supported as application property to specify the Db2 Warehouse cloud service credentials as JSON.
This would make integration with Db2 Warehouse service on IBM Cloud easier.

**Comment by anouri** [comment]
The new operator parameter is "jdbcCredentials"
"This optional parameter specifies the path name of the JSON file that contains the jdbc credentials: jdbcUser, jdbcPassword and jdbcUrl"
This parameter  should be supported as application configuration property.

**Comment by anouri** [comment]
Correction delivered in V1.4.3
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.4.3
