### ISSUE TITLE
 JDBCRun operator goes into a loop, trying to use error port

### ISSUE THREAD

**Issue by anouri** [IBMStreams/streamsx.jdbc#79]
The endless loop happens when:
The JDBCRun trying to use the optional output parameter "Error" and the SQL statement is invalid.

**Comment by ejpring** [comment]
The infinite loop also happens when a valid SQL statement fails because connectivity to the DB2 server has been lost.

**Comment by anouri** [comment]
Correction delivered in v.1.4.3
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.4.3
