### ISSUE TITLE
connection json looks for all lowercase "jdbcurl", however, all documentation and messages refer to "jdbcUrl".  Which should it be.

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.jdbc#86]
The documentation for the "credentials" parameter states: This optional parameter specifies the JSON string that contains the jdbc credentials: username, password and jdbcUrl

The code, however is: jdbcUrl = (String)obj.get("jdbcurl");

I have verified that json with 'jdbcUrl' does not work, however, 'jdbcurl' does work.

I believe by convention since json is case sensitive the correct value is 'jdbcurl', however, to be consistent with the parameter names and messages, I believe sticking with "jdbcUrl" is the best approach.

Currently if the value is not present in the json, the message that will be printed reflects: JDBC_URL_NOT_EXIST=CDIST2803E ''jdbcUrl'' is required to create JDBC connection.

**Comment by brandtol** [comment]
The reason for adding the credentials parameter was to allow using [Cloud Service Credentials](https://cloud.ibm.com/docs/resources?topic=resources-service_credentials#service_credentials) (for example for Db2 Warehouse service). The JSON string produced by the cloud service contains the lowercase version `jdbcurl` as key. So we should stick with the implementation, and fix the SPL doc.

**Comment by anouri** [comment]
We will support in the next release version also **jdbcUrl** in the JSON credentials file.

**Comment by anouri** [comment]
Corrected.
The credentials supports now 'jdbcurl' and also 'jdbcUrl'
Correction will be delivered in version 1.5.0

**Comment by anouri** [comment]
Corrected in streamsx.jdbc version 1.5.0
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.5.0
