### ISSUE TITLE
Application Configuration not working

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.jdbc#87]
Using an application configuration does not seem to work on the current Master branch.  Don Fox created a forum post about this, and I have verified looking at the code and testing that it is not coded properly.

**Comment by brandtol** [comment]
I added a correction for the compile time checks. 

The application configuration needs to contain the credentials parameter (Json string with attributes username, password and jdbcul, all lower case). Try the following format in your app config
```
credentials={"username":"xxx", "password":"yyy", "jdbcurl":"zzz"}
```

**Comment by bmwilli** [comment]
Thanks!

**Comment by anouri** [comment]
Corrected.
Correction will be delivered in version 1.5.0

**Comment by anouri** [comment]
Corrected in streamsx.jdbc version 1.5.0
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.5.0
