### ISSUE TITLE
Propose allowing jdbcUrl to be included in the properties file that can be pointed to by the jdbcProperties parameter

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.jdbc#88]
My customer would like to store the JDBC URL along with the username and password in the jdbcProperties file that currently available in the operator.   This would go along way toward consistency between credentials, appConfigName, and jdbcProperties parameters.

Any issues with adding that?

**Comment by anouri** [comment]
We will support also the parameter JdbcUrl in jdbcProperties file.

**Comment by bmwilli** [comment]
Great!  Thanks

**Comment by anouri** [comment]
Corrected.
Correction will be delivered in version 1.5.0

**Comment by anouri** [comment]
It works also with absolute path .
jdbcProperties: "etc/jdbc.properties" ;
or
jdbcProperties:  "/tmp/jdbc.properties" ;

**Comment by anouri** [comment]
Corrected in streamsx.jdbc version 1.5.0
https://github.com/IBMStreams/streamsx.jdbc/releases/tag/v1.5.0
